mgmt-rtr:
  hostname: 10.10.10.1
reg-rtr:
  hostname: 10.10.10.2
ham-rtr:
  hostname: 10.10.10.3
mid-rtr:
  hostname: 10.10.10.4
mgmt-sw:
  hostname: 10.10.10.5
ham-sw:
  hostname: 10.10.10.6
mid-sw:
  hostname: 10.10.10.7
